
  CREATE TABLE IF NOT EXISTS DOOR_READING (
    ID BIGINT(10) NOT NULL AUTO_INCREMENT,
    STATE TINYINT(1) NOT NULL,
    TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(), 
    PROCESSED TINYINT(1) NOT NULL DEFAULT 0, 
    DOOR_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT DOOR_READING_PK PRIMARY KEY (ID)
  );