
CREATE TABLE IF NOT EXISTS DOOR_READING (
  ID VARCHAR(50) NOT NULL UNIQUE,
  VALUE TINYINT(1) NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(), 
  PROCESSED TINYINT(1) NOT NULL DEFAULT 0, 
  DOOR_NAME VARCHAR(255) NOT NULL,
  LAST_UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT DOOR_READING_PK PRIMARY KEY (ID)
);

CREATE INDEX DOOR_READING_RPOCESSED_INDX ON DOOR_READING (PROCESSED);
CREATE INDEX DOOR_READING_CREATE_TIME_INDX ON DOOR_READING (CREATE_TIME);

CREATE TABLE IF NOT EXISTS DOOR (
  ID VARCHAR(50) NOT NULL UNIQUE,
  NAME VARCHAR(255) NOT NULL UNIQUE,
  CONSTRAINT DOOR_PK PRIMARY KEY (ID)
);

CREATE INDEX DOOR_NAME_INDX ON DOOR (NAME); 

CREATE TABLE IF NOT EXISTS DOOR_STATE_TRANSITION (
  ID VARCHAR(50) NOT NULL UNIQUE,
  DOOR_ID VARCHAR(50) NOT NULL,
  VALUE TINYINT(1) NOT NULL DEFAULT 0,
  ACTIVE TINYINT(1) NOT NULL DEFAULT 0,
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT DOOR_STATE_PK PRIMARY KEY (ID)
);

CREATE INDEX DOOR_STATE_TRANSITION_ACTIVE_INDX ON DOOR_STATE_TRANSITION (ACTIVE);
CREATE INDEX DOOR_STATE_TRANSITION_CREATE_TIME_INDX ON DOOR_STATE_TRANSITION (CREATE_TIME);